# conda env create -f environment.yml
name: fire
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.7
  - pandas
  - matplotlib
  - geopandas
  - cmasher
  - descartes
  - numpy
  - plotly
  - plotly_express
